### ISSUE TITLE
Django - Exception caused by attempting to fetch attributes for AnonymousUser

### ISSUE THREAD

**Issue by snags141** [bugsnag/bugsnag-python#329]
Hi there,

### Describe the bug
When using anonymous auth in django (for example, because you're using an external authentication system) the bugsnag report fails for me as bugsnag-python appears to expect user attributes such as full name. However when you're using anonymous users, there are no such attributes.

### Steps to reproduce
1. Write a class that extends BaseAuthentication and implement it in your view with authentication_classes[]
2. In authentication() of your class, return AnonymousUser which is imported from django.contrib.auth.models. As per the docs, authenticate() should return a two-tuple of (user, auth) if authentication succeeds. In this case, user is an instance of AnonymousUser.
3. Authenticate to the django app and attempt to raise an exception with bugsnag-python

### Environment
* Bugsnag version: 4.3.0
* Python version: 3.10.9
* Integration framework version:
    * Django: 3.2

### Example error message

```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/bugsnag/django/__init__.py", line 42, in add_django_request_to_notification
name = request.user.get_full_name()
AttributeError: type object 'AnonymousUser' has no attribute 'get_full_name'
```

### Associated code
`/bugsnag/django/__init__.py`
Line 35-49
```
if hasattr(request, 'user'):
        if callable(request.user.is_authenticated):
            is_authenticated = request.user.is_authenticated()
        else:
            is_authenticated = request.user.is_authenticated
        if is_authenticated:
            try:
                name = request.user.get_full_name()
                email = getattr(request.user, 'email', None)
                username = str(request.user.get_username())
                event.set_user(id=username, email=email, name=name)
            except Exception:
                event.config.logger.exception('Could not get user data')
    else:
        event.set_user(id=request.META['REMOTE_ADDR'])
```

### Possible Fix
Implement a check to see if the user is anonymous, before fetching the user attributes. [The following returns a Boolean](https://docs.djangoproject.com/en/stable/ref/contrib/auth/#django.contrib.auth.models.User.is_anonymous)
```
request.user.is_anonymous
```
Thank you. I'll be attempting to test this when I get time, at which point I'll raise a PR for review. In the meantime, raising for visibility. Hopefully a quick fix :)

**Comment by johnkiely1** [comment]
Hi @snags141, 

Thanks for reporting, we will fix this as soon as we can.

**Comment by imjoehaines** [comment]
Hi @snags141, I've been trying to reproduce this but haven't been able to

I created a new Django rest framework app with bugsnag-python and setup an authentication class like this:

```python
class ExampleAuthentication(authentication.BaseAuthentication):
    def authenticate(self, request):
        return (AnonymousUser(), None)
```

With a simple viewset that just raises:

```python
class UserViewSet(viewsets.ViewSet):
    queryset = User.objects.all()
    authentication_classes = [ExampleAuthentication]

    def list(self, request):
        raise Exception('oh no')
```

This goes through the `ExampleAuthentication` and reports an error to bugsnag, but doesn't fail on `get_full_name` because [`AnonymousUser.is_authenticated` always returns `False`](https://docs.djangoproject.com/en/4.1/ref/contrib/auth/#anonymoususer-object), so it never reaches the line calling `get_full_name` in our Django integration

Have you customised the `AnonymousUser` class so that `is_authenticated` returns `True`? Otherwise I'm not sure how this error could be triggered

I'm not sure it makes sense to use `is_anonymous` as well as (or instead of) `is_authenticated` because they should be opposites; if the user is anonymous they're not authenticated and vice versa. [The Django docs even say to prefer using `is_authenticated`](https://docs.djangoproject.com/en/4.1/ref/contrib/auth/#django.contrib.auth.models.User.is_anonymous) so the existing check should be correct unless I've missed something

**Comment by snags141** [comment]
Hi @imjoehaines, thanks for looking into this for me.

I think I've found the issue. When I was returning my AnonymousUser in my authenticate() method, I was returning the class instead of an instance. 
I should have been doing `return (AnonymousUser(), None)` as in your code above, but instead I was doing `return (AnonymousUser, None)`. 

This wasn't immediately obvious, because if you print the value of is_authenticated you get `<property object at 0x7f129f255760>`.
Because of the way Python evaluates `if is_authenticated:` as is written in the bugsnag-python code, it then treats this as true, resulting in the error I ran into. A more accurate comparison would be the direct `if is_authenticated == True:` instead.

Thanks again - All appears to be working now. 👍
